"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "l",
  ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [
    "S",
  ], run = '''shell "$SHELL" --block --confirm''', desc = "Open shell here" },
  { on = [
    "f",
  ], run = "plugin searchjump", desc = "searchjump mode" },
  { on = [
    "C",
  ], run = "plugin compress", desc = "Compress selected files" },
  { on = [ "g", "g" ], run  = "arrow -99999999", desc = "Move cursor to the top" },
  { on = [ "G" ], run  = "arrow 99999999", desc = "Move cursor to the bottom" },
  { on = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "K", run = "arrow -50%", desc = "Move cursor up half page" },
  { on = "J", run = "arrow 50%", desc = "Move cursor down half page" },
  { on = "<A-k>", run = "arrow -5", desc = "Move cursor up half page" },
  { on = "<A-j>", run = "arrow 5", desc = "Move cursor down half page" },
  # ╭──────────────────────────────────────────────────────────╮
  # │ bookmarks                                                │
  # ╰──────────────────────────────────────────────────────────╯
  { on = [ "m" ], run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark" },
  { on = [ "'" ], run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark" },
  { on = [ "b", "d" ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
  { on = [ "b", "D" ], run = "plugin bookmarks --args=delete_all", desc = "Delete all bookmark" },
  { on = [ "P" ], run = "paste --force", desc = "Paste and overwrite existing files" },
  # { on = [
  #   "f",
  #   "g",
  # ], run = "plugin fg", desc = "find file by content (fuzzy match)" },
  # { on = [
  #   "f",
  #   "G",
  # ], run = "plugin fg --args='rg'", desc = "find file by content (ripgrep match)" },
  # { on = [
  #   "f",
  #   "n",
  # ], run = "plugin fg --args='fzf'", desc = "find file by filename" },
  # { on = [
  #   "f",
  #   "f",
  # ], run = "filter --smart", desc = "Filter files" },
  # { on = [
  #   "f",
  #   "F",
  # ], run = "plugin smart-filter", desc = "Smart Filter" },
  # { on = "S", run = "search fd", desc = "Search files by name using fd" },
  { on = [
    "T",
  ], run = "plugin --sync hide-preview", desc = "Hide or show the preview" },
]

append_keymap = [
  { on = [
    "t",
  ], run = "tab_create --current", desc = "Create a new tab using the current path" },
  { on = [
    "e",
  ], run = "open", desc = "Open the selected files" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Open the selected files interactively" },
  { on = [
    "g",
    "/",
  ], run = "cd /", desc = "Go to the / directory" },
  { on = [
    "g",
    "d",
  ], run = "cd ~/Downloads/", desc = "Go to the Downloads directory" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/Videos/", desc = "Go to the videos directory" },
  { on = [
    "g",
    "f",
    "p",
  ], run = "cd ~/Pictures/", desc = "Go to the images directory" },
  { on = [
    "g",
    "f",
    "s",
  ], run = "cd ~/Pictures/Screenshots/", desc = "Go to the screenshots directory" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documents/", desc = "Go to the docs directory" },
  { on = [
    "g",
    "f",
    "c",
  ], run = "cd ~/.config", desc = "Go to the config directory" },
  { on = [
    "g",
    "f",
    "g",
  ], run = "cd ~/Clone", desc = "Go to the Clone directory" },
  { on = [
    "g",
    "f",
    "l",
  ], run = "cd ~/.local", desc = "Go to the .local directory" },
  { on = [
    "g",
    "f",
    "n",
  ], run = "cd ~/.config/nvim/", desc = "Go to the nvim directory" },
  { on = [
    "g",
    "f",
    "t",
  ], run = "cd ~/Clone/typst-book-template/", desc = "Go to the typst_book_template directory" },
  { on = [
    "g",
    "f",
    "y",
  ], run = "cd ~/.config/yazi/", desc = "Go to the yazi directory" },
  { on = [
    "g",
    "f",
    "w",
  ], run = "cd ~/.config/wezterm/", desc = "Go to the wezterm directory" },
  { on = [
    "g",
    "f",
    "h",
  ], run = "cd ~/.config/hypr", desc = "Go to the hypr directory" },
]

[input]

prepend_keymap = [{ on = ["<Esc>"], run = "close", desc = "Cancel input" }]

[completion]
prepend_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move cursor down" },
]
