[icon]
prepend_dirs = [
  { name = "desktop", text = "" },
  { name = "dev", text = "" },
  { name = "documents", text = "" },
  { name = "downloads", text = "" },
  { name = "music", text = "" },
  { name = "games", text = "󰊴" },
  { name = "pictures", text = "" },
  { name = "videos", text = "" },
]

[flavor]
use = "catppuccin-macchiato"
# dark = "catppuccin-macchiato"
# dark = "tokyonight-night"
# light = "tokyonight-night"

# use = "catppuccin-mocha"
# dark = "catppuccin-mocha"

# dark = "dracula"

# use = "sunset"
# dark = "sunset"

# dark = "flexoki-dark"
# light = "flexoki-light"

# use = "ayu-dark"
# dark = "ayu-dark"

# ya pack -a mukhlisakbr/solarized-osaka
# dark = "solarized-osaka"
# light = "solarized-osaka"
