"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
# use = "catppuccin-macchiato"
# dark = "catppuccin-macchiato"
# dark = "tokyonight-night"
# light = "tokyonight-night"

# ya pack -a mukhlisakbr/solarized-osaka
dark = "solarized-osaka"
light = "solarized-osaka"
